package com.Dibyanshu.ControlStatements;

import java.util.Random;

public class RandomGeneration {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		
		Random random = new Random();
		
		//Plain random number
		int randomNumber = random.nextInt();
		System.out.println("Random Number generated is : "+randomNumber);
		
		//Upper range
		randomNumber = random.nextInt(1000);
		System.out.println("Random Number generated by defined upper range is : "+randomNumber);
		
		//Between certain range by shifting
		randomNumber = random.nextInt(1000)+1;//1-1000
		System.out.println("Random Number generated by defined range[Here, 1- 1000] is : "+randomNumber);

	}

}
